/// Flutter icons FlickyIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FlickyIcons
///      fonts:
///       - asset: fonts/FlickyIcons.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class FlickyIcons {
  FlickyIcons._();

  static const _kFontFam = 'FlickyIcons';
  static const String? _kFontPkg = null;

  static const IconData access_time = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_circle = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_circle_outline = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_alert = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData airline_seat_individual_suite = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alarm = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData announcement = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData apps = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData assessment = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData audiotrack = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData autorenew = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_std = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_alert = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData block = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bluetooth = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bluetooth_disabled = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brightness_3 = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brightness_4 = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brightness_7 = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_circle = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_box_outline_blank = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData delete = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData desktop_mac = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dns = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData highlight = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData keyboard_voice = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lightbulb_outline = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData music_note = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData phone_android = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData power = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData queue_music = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData report_problem = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toys = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timer = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timeline = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wb_sunny = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
